services:
  caddy:
    container_name: caddy
    build:
      context: ./caddy
    restart: unless-stopped
    environment:
      SERVER_NAME: "https://localhost"
      FASTAPI_API_SERVER_ADDRESS: "fastapi-tcp:8080"
      FLASK_API_SERVER_ADDRESS: "flask-tcp:8080"
      NESTJS_API_SERVER_ADDRESS: "nestjs-tcp:8080"
      EXPRESS_API_SERVER_ADDRESS: "express-tcp:8080"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
    ports:
      - "443:443"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - "fastapi_socket:/tmp/fastapi"
      - "flask_socket:/tmp/flask"
      - "nestjs_socket:/tmp/nestjs"
      - "./ssl:/etc/nginx/ssl"

  fastapi-uds:
    container_name: fastapi-uds
    build:
      context: .
      dockerfile: python/fastapi/Dockerfile
    tty: true
    environment:
      PREFIX: "/fastapi-uds/v1"
    platform: linux/arm64
    volumes:
      - "./python/fastapi/src:/opt/app/src"
      - "fastapi_socket:/opt/app/tmp"
    command: uvicorn main:app --uds /opt/app/tmp/uvicorn.sock

  fastapi-tcp:
    container_name: fastapi-tcp
    build:
      context: .
      dockerfile: python/fastapi/Dockerfile
    ports:
      - "8080:8080"
    tty: true
    environment:
      PREFIX: "/fastapi-tcp/v1"
    platform: linux/arm64
    volumes:
      - "./python/fastapi/src:/opt/app/src"
    command: uvicorn main:app --host=0.0.0.0 --port=8080

  flask-tcp:
    container_name: flask-tcp
    build:
      context: .
      dockerfile: python/flask/Dockerfile
    ports:
      - "8081:8080"
    tty: true
    environment:
      PREFIX: "/flask-tcp/v1"
    platform: linux/arm64
    volumes:
      - "./python/flask/src:/opt/app/src"
    command: gunicorn main:app --bind 0.0.0.0:8080

  nestjs-tcp:
    container_name: nestjs-tcp
    build:
      context: ./typescript/nestjs
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    tty: true
    environment:
      PREFIX: "/nestjs-tcp/v1"
    volumes:
      - "./src:/opt/app/src"

  express-tcp:
    container_name: express-tcp
    build:
      context: ./typescript/express
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    tty: true
    environment:
      PREFIX: "/express-tcp/v1"
    volumes:
      - "./typescript/express/src:/opt/app/src"

volumes:
  fastapi_socket:
  flask_socket:
  nestjs_socket:
