services:
  caddy:
    container_name: caddy
    build:
      context: ./caddy
    restart: unless-stopped
    environment:
      SERVER_NAME: "https://localhost"
      FASTAPI_API_SERVER_ADDRESS: "fastapi:8080"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
    ports:
      - "443:443"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - "fastapi_socket:/tmp/fastapi"
      - "./ssl:/etc/nginx/ssl"

  fastapi-uds:
    container_name: fastapi-uds
    build:
      context: .
      dockerfile: python/fastapi/Dockerfile
    tty: true
    environment:
      PREFIX: "/fastapi-uds/v1"
    platform: linux/arm64
    volumes:
      - "./python/fastapi/src:/opt/app/src"
      - "fastapi_socket:/opt/app/tmp"
    command: uvicorn main:app --uds /opt/app/tmp/uvicorn.sock

  fastapi-tcp:
    container_name: fastapi-tcp
    build:
      context: .
      dockerfile: python/fastapi/Dockerfile
    ports:
      - "8080:8080"
    tty: true
    environment:
      PREFIX: "/fastapi-tcp/v1"
    platform: linux/arm64
    volumes:
      - "./python/fastapi/src:/opt/app/src"
    command: uvicorn main:app --host=0.0.0.0 --port=8080

volumes:
  fastapi_socket:
