version: '3'

tasks:

  default:
    cmds:
      - task -l --sort none
    silent: true

  locust:
    desc: deploy batch
    internal: true
    cmds:
      - |
        HOST={{.host}} URL={{.url}} \
        rye run locust -f ./locust/{{.locustfile}} \
        --users 512 \
        --spawn-rate 64 \
        --csv ./reports/{{.language}}_{{.framework}}_{{.proxy}}_{{.protocol}} \
        --headless \
        --only-summary \
        --run-time 1m \
        --processes 4

  nginx-uds-fastapi:
    desc: fastapi - uds; e.g. $ task fastapi-uds
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /fastapi-uds/v1/user
          language: python
          framework: fastapi
          proxy: nginx
          protocol: uds

  nginx-tcp-fastapi:
    desc: fastapi - tcp; e.g. $ task fastapi-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /fastapi-tcp/v1/user
          language: python
          framework: fastapi
          proxy: nginx
          protocol: tcp

  caddy-tcp-fastapi:
    desc: fastapi - caddy tcp; e.g. $ task caddy-tcp-fastapi
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost
          url: /fastapi-tcp/v1/user
          language: python
          framework: fastapi
          proxy: caddy
          protocol: tcp

  bare-tcp-fastapi:
    desc: fastapi - tcp; e.g. $ task bare-tcp-fastapi
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8080
          url: /fastapi-tcp/v1/user
          language: python
          framework: fastapi
          proxy: none
          protocol: tcp

  bare-tcp-flask:
    desc: flask - tcp; e.g. $ task bare-tcp-flask
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8081
          url: /flask-tcp/v1/user
          language: python
          framework: flask
          proxy: none
          protocol: tcp

  bare-tcp-nestjs:
    desc: nestjs - tcp; e.g. $ task bare-tcp-nestjs
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8082
          url: /nestjs-tcp/v1/user
          language: typescript
          framework: nestjs
          proxy: none
          protocol: tcp

  nginx-tcp-nestjs:
    desc: nestjs - nginx tcp; e.g. $ task nginx-tcp-nestjs
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /nestjs-tcp/v1/user
          language: typescript
          framework: nestjs
          proxy: nginx
          protocol: tcp

  caddy-tcp-nestjs:
    desc: nestjs - caddy tcp; e.g. $ task caddy-tcp-nestjs
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /nestjs-tcp/v1/user
          language: typescript
          framework: nestjs
          proxy: caddy
          protocol: tcp

  bare-tcp-express:
    desc: express - tcp; e.g. $ task bare-tcp-express
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8083
          url: /express-tcp/v1/user
          language: typescript
          framework: express
          proxy: none
          protocol: tcp

  nginx-tcp-express:
    desc: express - nginx tcp; e.g. $ task nginx-tcp-express
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /express-tcp/v1/user
          language: typescript
          framework: express
          proxy: nginx
          protocol: tcp

  caddy-tcp-express:
    desc: express - caddy tcp; e.g. $ task caddy-tcp-express
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /express-tcp/v1/user
          language: typescript
          framework: express
          proxy: caddy
          protocol: tcp

  bare-tcp-fastify:
    desc: fastify - tcp; e.g. $ task bare-tcp-fastify
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8088
          url: /fastify-tcp/v1/user
          language: typescript
          framework: fastify
          proxy: none
          protocol: tcp

  nginx-tcp-fastify:
    desc: fastify - nginx tcp; e.g. $ task nginx-tcp-fastify
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /fastify-tcp/v1/user
          language: typescript
          framework: fastify
          proxy: nginx
          protocol: tcp

  caddy-tcp-fastify:
    desc: fastify - caddy tcp; e.g. $ task caddy-tcp-fastify
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /fastify-tcp/v1/user
          language: typescript
          framework: fastify
          proxy: caddy
          protocol: tcp

  bare-tcp-rocket:
    desc: rocket - tcp; e.g. $ task rocket-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8084
          url: /rocket-tcp/v1/user
          language: rust
          framework: rocket
          proxy: none
          protocol: tcp

  nginx-tcp-rocket:
    desc: rocket - nginx tcp; e.g. $ task nginx-tcp-rocket
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /rocket-tcp/v1/user
          language: rust
          framework: rocket
          proxy: nginx
          protocol: tcp

  caddy-tcp-rocket:
    desc: rocket - caddy tcp; e.g. $ task caddy-tcp-rocket
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /rocket-tcp/v1/user
          language: rust
          framework: rocket
          proxy: caddy
          protocol: tcp

  bare-tcp-warp:
    desc: warp - tcp; e.g. $ task warp-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8085
          url: /warp-tcp/v1/user
          language: rust
          framework: warp
          proxy: none
          protocol: tcp

  nginx-tcp-warp:
    desc: warp - nginx tcp; e.g. $ task nginx-tcp-warp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /warp-tcp/v1/user
          language: rust
          framework: warp
          proxy: nginx
          protocol: tcp

  caddy-tcp-warp:
    desc: warp - caddy tcp; e.g. $ task caddy-tcp-warp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /warp-tcp/v1/user
          language: rust
          framework: warp
          proxy: caddy
          protocol: tcp

  bare-tcp-axum:
    desc: axum - tcp; e.g. $ task axum-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8086
          url: /axum-tcp/v1/user
          language: rust
          framework: axum
          proxy: none
          protocol: tcp

  nginx-tcp-axum:
    desc: axum - nginx tcp; e.g. $ task nginx-tcp-axum
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /axum-tcp/v1/user
          language: rust
          framework: axum
          proxy: nginx
          protocol: tcp

  caddy-tcp-axum:
    desc: axum - caddy tcp; e.g. $ task caddy-tcp-axum
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /axum-tcp/v1/user
          language: rust
          framework: axum
          proxy: caddy
          protocol: tcp

  bare-tcp-gin:
    desc: gin - tcp; e.g. $ task gin-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8087
          url: /gin-tcp/v1/user
          language: go
          framework: gin
          proxy: none
          protocol: tcp

  nginx-tcp-gin:
    desc: gin - nginx tcp; e.g. $ task nginx-tcp-gin
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /gin-tcp/v1/user
          language: go
          framework: gin
          proxy: nginx
          protocol: tcp

  caddy-tcp-gin:
    desc: gin - caddy tcp; e.g. $ task caddy-tcp-gin
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /gin-tcp/v1/user
          language: go
          framework: gin
          proxy: caddy
          protocol: tcp

  bare-tcp-fiber:
    desc: fiber - tcp; e.g. $ task fiber-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8088
          url: /fiber-tcp/v1/user
          language: go
          framework: fiber
          proxy: none
          protocol: tcp

  nginx-tcp-fiber:
    desc: fiber - nginx tcp; e.g. $ task nginx-tcp-fiber
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /fiber-tcp/v1/user
          language: go
          framework: fiber
          proxy: nginx
          protocol: tcp

  caddy-tcp-fiber:
    desc: fiber - caddy tcp; e.g. $ task caddy-tcp-fiber
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /fiber-tcp/v1/user
          language: go
          framework: fiber
          proxy: caddy
          protocol: tcp

  benchmark-all:
    desc: all; e.g. $ task benchmark-all
    cmds:
      - task: bare-tcp-fastapi
      - task: nginx-uds-fastapi
      - task: nginx-tcp-fastapi
      - task: caddy-tcp-fastapi
      - task: bare-tcp-flask
      - task: bare-tcp-nestjs
      - task: nginx-tcp-nestjs
      - task: bare-tcp-express
      - task: nginx-tcp-express
      - task: bare-tcp-fastify
      - task: nginx-tcp-fastify
      - task: bare-tcp-rocket
      - task: nginx-tcp-rocket
      - task: bare-tcp-warp
      - task: nginx-tcp-warp
      - task: bare-tcp-axum
      - task: nginx-tcp-axum
      - task: bare-tcp-gin
      - task: nginx-tcp-gin
      - task: bare-tcp-fiber
      - task: nginx-tcp-fiber
#      - task: caddy-tcp-nestjs
#      - task: caddy-tcp-express
#      - task: caddy-tcp-rocket
#      - task: caddy-tcp-gin
#      - task: caddy-tcp-fiber
      - rye run python ./scripts/summarize.py
