version: '3'

tasks:

  default:
    cmds:
      - task -l --sort none
    silent: true

  locust:
    desc: deploy batch
    internal: true
    cmds:
      - |
        rye run locust -f ./locust/{{.locustfile}} \
        --users 512 --spawn-rate 64 --csv ./reports/{{.locustfile}} \
        --headless --only-summary --run-time 1m

  nginx-uds-fastapi:
    desc: fastapi - uds; e.g. $ task fastapi-uds
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "nginx_uds_fastapi.py"

  nginx-tcp-fastapi:
    desc: fastapi - uds; e.g. $ task fastapi-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "nginx_tcp_fastapi.py"

  caddy-tcp-fastapi:
    desc: fastapi - uds; e.g. $ task fastapi-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "caddy_tcp_fastapi.py"

  bare-tcp-fastapi:
    desc: fastapi - uds; e.g. $ task fastapi-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "bare_tcp_fastapi.py"

  benchmark-all:
    desc: all; e.g. $ task benchmark-all
    cmds:
      - task: bare-tcp-fastapi
      - task: nginx-uds-fastapi
      - task: nginx-tcp-fastapi
      - task: caddy-tcp-fastapi
      - rye run python ./scripts/summarize.py
