version: '3'

tasks:

  default:
    cmds:
      - task -l --sort none
    silent: true

  locust:
    desc: deploy batch
    internal: true
    cmds:
      - |
        HOST={{.host}} URL={{.url}} rye run locust -f ./locust/{{.locustfile}} \
        --users 512 --spawn-rate 64 --csv ./reports/{{.locustfile}} \
        --headless --only-summary --run-time 1m --processes 4

  nginx-uds-fastapi:
    desc: fastapi - uds; e.g. $ task fastapi-uds
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /fastapi-uds/v1/user

  nginx-tcp-fastapi:
    desc: fastapi - tcp; e.g. $ task fastapi-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /fastapi-tcp/v1/user

  caddy-tcp-fastapi:
    desc: fastapi - caddy tcp; e.g. $ task caddy-tcp-fastapi
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost
          url: /fastapi-tcp/v1/user

  bare-tcp-fastapi:
    desc: fastapi - tcp; e.g. $ task bare-tcp-fastapi
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8080
          url: /fastapi-tcp/v1/user

  bare-tcp-flask:
    desc: flask - tcp; e.g. $ task bare-tcp-flask
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8081
          url: /flask-tcp/v1/user

  bare-tcp-nestjs:
    desc: nestjs - tcp; e.g. $ task bare-tcp-nestjs
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8082
          url: /nestjs-tcp/v1/user

  nginx-tcp-nestjs:
    desc: nestjs - nginx tcp; e.g. $ task nginx-tcp-nestjs
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /nestjs-tcp/v1/user

  caddy-tcp-nestjs:
    desc: nestjs - caddy tcp; e.g. $ task caddy-tcp-nestjs
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /nestjs-tcp/v1/user

  bare-tcp-express:
    desc: express - tcp; e.g. $ task bare-tcp-express
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8083
          url: /express-tcp/v1/user

  nginx-tcp-express:
    desc: express - nginx tcp; e.g. $ task nginx-tcp-express
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /express-tcp/v1/user

  caddy-tcp-express:
    desc: express - caddy tcp; e.g. $ task caddy-tcp-express
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /express-tcp/v1/user

  bare-tcp-rocket:
    desc: rocket - tcp; e.g. $ task rocket-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8084
          url: /rocket-tcp/v1/user

  nginx-tcp-rocket:
    desc: rocket - nginx tcp; e.g. $ task nginx-tcp-rocket
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /rocket-tcp/v1/user

  caddy-tcp-rocket:
    desc: rocket - caddy tcp; e.g. $ task caddy-tcp-rocket
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /rocket-tcp/v1/user

  bare-tcp-warp:
    desc: warp - tcp; e.g. $ task warp-tcp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: http://localhost:8085
          url: /warp-tcp/v1/user

  nginx-tcp-warp:
    desc: warp - nginx tcp; e.g. $ task nginx-tcp-warp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:8443
          url: /warp-tcp/v1/user

  caddy-tcp-warp:
    desc: warp - caddy tcp; e.g. $ task caddy-tcp-warp
    internal: true
    cmds:
      - task: locust
        vars:
          locustfile: "api_v1_user.py"
          host: https://localhost:443
          url: /warp-tcp/v1/user

  benchmark-all:
    desc: all; e.g. $ task benchmark-all
    cmds:
      - task: bare-tcp-fastapi
      - task: nginx-uds-fastapi
      - task: nginx-tcp-fastapi
      - task: caddy-tcp-fastapi
      - task: bare-tcp-flask
      - task: bare-tcp-nestjs
      - task: nginx-tcp-nestjs
      - task: bare-tcp-express
      - task: nginx-tcp-express
      - task: bare-tcp-rocket
      - task: nginx-tcp-rocket
      - task: bare-tcp-warp
      - task: nginx-tcp-warp
#      - task: caddy-tcp-nestjs
#      - task: caddy-tcp-express
#      - task: caddy-tcp-rocket
      - rye run python ./scripts/summarize.py
